[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
namespace_packages = True
strict_optional = True

[mypy-tests.*]
ignore_errors = True

[mypy-setuptools]
ignore_missing_imports = True

[mypy-aiohttp]
ignore_missing_imports = True

[mypy-beautifulsoup4]
ignore_missing_imports = True

[mypy-cloudscraper]
ignore_missing_imports = True

[mypy-fake_useragent]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-customtkinter]
ignore_missing_imports = True